name: Test workflow


on:
  workflow_dispatch:
    inputs:
      name: 
        description: My name
        type: string
        required: false

jobs: 
  prepare-wfs:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/act_${{github.run_id}}.yaml
      - uses: actions/github-script@v7
        id: get-repos-list
        with:
          result-encoding: string
          script: |
            const repos = await github.rest.repos.listForUser.paginate({
              username: '${{ github.repository_owner }}',
            });
            console.log(JSON.stringify(repos))
            