name: Test workflow


on:
  workflow_dispatch:
    inputs:
      name: 
        description: My name
        type: string
        required: false

jobs: 
  prepare-wfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./github/actions/act_${{github.run_id}}.yaml
      - uses: actions/github-script@v7
        id: get-repos-list
        with:
          node-version: 20
      - run: npm ci
      - run: npm run prepare

  tests:
    runs-on: ubuntu-latest
    needs:
      - prepare-wfs
    steps:
      - uses: roamingowl/dwf-test_workflows/.github/workflows/tests.yaml

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare-wfs
    steps:
      - uses: roamingowl/dwf-test_workflows/.github/workflows/tests.yaml

